services:
  microservice1:
    image: business-client-management-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: devsudb
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      KAFKA_BROKER: kafka:9092

  microservice2:
    image: business-account-management-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - kafka
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: devsudb
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      KAFKA_BROKER: kafka:9092

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devsudb
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  zookeeper:
    image: 'zookeeper:3.5'
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - '9092:9092'